server:
  port: 8070
  error:
    include-message: always
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
#            allowedOrigins: "*"
            allowedOrigins: http://localhost:3000
            allowedMethods:
              - GET
              - POST
            allowCredentials: true

#      default-filters:
#        - DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
#        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
  application:
    name: gateway
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8040/eureka
    eureka-service-url-poll-interval-seconds: 10
